---
title: "Boston housing"
author: "Tristan-Mihai Radulescu, Hugo Ponthieu, Benoit Planche"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
library(ggplot2)
library(knitr)
library(tidyverse)
library(broom)
library(GGally)
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
BostonHousing <- read.csv("./BostonHousing.csv")
head(BostonHousing)
str(BostonHousing)
```

## Histogram on Medv

```{r}
hist(BostonHousing$medv, breaks = 15)
```

On this histogram, we can see that the distribution is not normal. The mode is at arout 20 to 25.


## Linear regression

```{r}
pairs(
  data = BostonHousing,
  ~.
)
```

```{r}
lin_reg <- lm(medv ~ rm, data = BostonHousing)
ggplot(data = BostonHousing, aes(x = medv, y = rm)) +
  geom_point() +
  geom_smooth(method = "lm")
```

## Linear Multiple Regression

### Backward Elimination

```{r}
model <- lm(medv ~ ., data = BostonHousing)

summary(model)

backward_model <- step(model, direction = "backward", trace = FALSE)

summary(backward_model)


plot(backward_model)
```

## Perfect linear regression

```{r}
lin_reg <- lm(medv ~ medv, data = BostonHousing)
plot(lin_reg)
```

## Worst linear regression

```{r}
lin_reg <- lm(medv ~ indus, data = BostonHousing)
plot(lin_reg)
```
Can you make a box plot of the value of the rivers in the BostonHousing dataset? 

```{r}
# Load necessary libraries
library(ggplot2)

# Create a boxplot for 'medv' colored by 'chas'
ggplot(BostonHousing, aes(x = factor(chas), y = medv, fill = factor(chas))) +
  geom_boxplot() +
  labs(title = "Boxplot of Median Home Values by River Boundary",
       x = "Bounds River",
       y = "Median Home Value (in $1000s)",
       fill = "Bounds River") +
  scale_fill_manual(values = c("No" = "red", "Yes" = "blue")) +
  theme_minimal()


```
